New components and refactoring
TerraHubCorp/terraform-aws-landing-zone pull request #139
Opened 2019-11-01 21:22 UTC by vcalmic

## Description

Fixes # (issue)

## Type of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a change to the documentation

## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

### Test Configuration
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have checked that my changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2019-11-04 12:31 UTC, euliancom requested changes

2019-11-04 12:31 UTC, euliancom commented on components/landing_zone_cloudtrail/.terrahub.yml
> +terraform:
Please, remove this param.

2019-11-04 12:31 UTC, euliancom commented on components/landing_zone_iam_role_policy_attachment/default.tfvars
> +}
Please, add new line :)

2019-11-04 12:31 UTC, euliancom commented on components/landing_zone_ssm_association_by_targets/default.tfvars
> +    # Key = "Value"
Please, delete this line

2019-11-04 16:54 UTC, euliancom approved these changes

2019-11-11 14:01 UTC, eistrati approved these changes

2019-11-11 14:02 UTC, merged