Building terraform v0.12+ compatible version
TerraHubCorp/terraform-aws-landing-zone pull request #46
Opened 2019-07-30 21:39 UTC by eistrati

2019-07-30 21:50 UTC, euliancom requested changes

2019-07-30 21:50 UTC, euliancom commented on examples/example_landing_zone_reader/README.md
> +    subnet_ids         = [local.landing_zone_subnet_ids["default"]]
Please change this line with `subnet_ids         = local.landing_zone_subnet_ids["default"]`

2019-07-30 21:50 UTC, euliancom commented on examples/example_landing_zone_reader/README.md
> +    security_group_ids = [local.landing_zone_security_group_ids["default"]]
Please change this line with `security_group_ids = local.landing_zone_security_group_ids["default"]`

2019-07-31 08:45 UTC, euliancom approved these changes

2019-07-31 08:45 UTC, vcalmic approved these changes

2019-07-31 08:46 UTC, merged